### ISSUE TITLE
DeviceEntryType error after upgrade to 1.1.4 version

### ISSUE THREAD

**Issue by silvanverschuur** [golles/ha-knmi#11]
The component doesn't work anymore after updating the component to version 1.1.4.

I'm running Home Assistant version 2021.11.0

## Debug log

```text
Logger: homeassistant.setup
Source: setup.py:316
First occurred: 08:06:32 (3 occurrences)
Last logged: 08:06:33

Unable to prepare setup for platform knmi.binary_sensor: Platform not found (cannot import name 'DeviceEntryType' from 'homeassistant.helpers.device_registry' (/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/device_registry.py)).
Unable to prepare setup for platform knmi.weather: Platform not found (cannot import name 'DeviceEntryType' from 'homeassistant.helpers.device_registry' (/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/device_registry.py)).
Unable to prepare setup for platform knmi.sensor: Platform not found (cannot import name 'DeviceEntryType' from 'homeassistant.helpers.device_registry' (/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/device_registry.py)).

```

**Comment by golles** [comment]
I'm not sure what is the best way forward, `DeviceEntryType` was introduced in 2021.12 I think, upgrading HA to that version would fix your issue.

I have a branch with a hotfix that you could use as well: https://github.com/golles/ha-knmi/tree/2021.11-fix

Let me know if this helps for you
(In the meantime I need to think about how I should accept new features from HA)

**Comment by silvanverschuur** [comment]
@golles That's no problem. I didn't know the `DeviceEntryType` was introduced in 2021.12.

I will upgrade my HA instance to fix it. Thanks.

**Comment by golles** [comment]
It was introduced here: https://github.com/home-assistant/core/pull/59940/files#diff-cf3556489ca520b322444a92a9232b9473ee68ee564de8e305f33fa734ec649a

I think it was a bit unlucky that I did all this refactoring just after 2021.12 release :-) 

Let me know if it's still broken after the upgrade

**Comment by silvanverschuur** [comment]
@golles I've upgraded Home Assistant to the latest version and now everything works fine.

**Comment by golles** [comment]
Good to hear and thanks for reporting back!
